"""Tests for manifest flag resolution and profile rendering."""

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import profile_resolver

HAS_YAML = importlib.util.find_spec("yaml") is not None


class ResolveFlagsTests(unittest.TestCase):
    def test_empty_manifest_uses_desktop_default(self):
        flags = profile_resolver.resolve_flags({}, "windows")
        self.assertEqual(flags, profile_resolver.PROFILE_DEFAULTS["desktop-default"])

    def test_platform_profile_selection(self):
        manifest = {"profiles": {"base": "desktop-default", "web": "web-small"}}
        flags = profile_resolver.resolve_flags(manifest, "web")
        self.assertEqual(flags["optimize"], "size")
        self.assertEqual(flags["threads"], "no")
        self.assertEqual(flags["dlink_enabled"], "no")

    def test_disable_feature(self):
        manifest = {"features": {"disable": ["gdscript"]}}
        flags = profile_resolver.resolve_flags(manifest, "windows")
        self.assertEqual(flags["module_gdscript_enabled"], "no")

    def test_platform_enable_overrides_global_disable(self):
        manifest = {
            "features": {"disable": ["physics_3d"]},
            "platforms": {"windows": {"enable": ["physics_3d"]}},
        }
        flags = profile_resolver.resolve_flags(manifest, "windows")
        self.assertEqual(flags["disable_physics_3d"], "no")
        self.assertEqual(flags["module_godot_physics_3d_enabled"], "yes")

    def test_platform_disables_apply_to_that_platform_only(self):
        manifest = {"platforms": {"web": {"disable": ["physics_2d"]}}}
        web_flags = profile_resolver.resolve_flags(manifest, "web")
        windows_flags = profile_resolver.resolve_flags(manifest, "windows")
        self.assertEqual(web_flags["disable_physics_2d"], "yes")
        self.assertNotIn("disable_physics_2d", windows_flags)

    def test_unknown_feature_raises(self):
        manifest = {"features": {"disable": ["bogus_feature"]}}
        with self.assertRaises(ValueError):
            profile_resolver.resolve_flags(manifest, "windows")

    def test_unknown_profile_raises(self):
        manifest = {"profiles": {"base": "bogus-profile"}}
        with self.assertRaises(ValueError):
            profile_resolver.resolve_flags(manifest, "windows")

    def test_empty_yaml_sections_are_tolerated(self):
        # Empty sections in YAML (e.g. a bare `features:` line) parse to None.
        manifests = [
            {"features": None},
            {"features": {"enable": None, "disable": None}},
            {"platforms": None},
            {"platforms": {"windows": None}},
            {"platforms": {"windows": {"enable": None}}},
        ]
        for manifest in manifests:
            flags = profile_resolver.resolve_flags(manifest, "windows")
            self.assertEqual(flags, profile_resolver.PROFILE_DEFAULTS["desktop-default"], manifest)


class RenderProfileTests(unittest.TestCase):
    def test_sorted_quoted_output(self):
        rendered = profile_resolver.render_profile({"b_flag": "2", "a_flag": "1"})
        lines = rendered.splitlines()
        self.assertEqual(lines[0], "# Generated by gdcpps.")
        self.assertIn('a_flag = "1"', lines)
        self.assertIn('b_flag = "2"', lines)
        self.assertLess(lines.index('a_flag = "1"'), lines.index('b_flag = "2"'))


@unittest.skipUnless(HAS_YAML, "PyYAML not installed")
class LoadManifestTests(unittest.TestCase):
    def _write_manifest(self, root: Path, text: str) -> None:
        (root / "gdcpps.yaml").write_text(text, encoding="utf-8")

    def test_loads_mapping(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self._write_manifest(root, "project:\n  name: demo\n")
            manifest = profile_resolver.load_manifest(root)
        self.assertEqual(manifest["project"]["name"], "demo")

    def test_empty_manifest_is_empty_dict(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self._write_manifest(root, "")
            self.assertEqual(profile_resolver.load_manifest(root), {})

    def test_non_mapping_manifest_raises(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self._write_manifest(root, "- not\n- a\n- mapping\n")
            with self.assertRaises(ValueError):
                profile_resolver.load_manifest(root)


if __name__ == "__main__":
    unittest.main()
