#!/usr/bin/env python

import os

Import("env")
Import("env_modules")

env_spinning_cube = env_modules.Clone()

project_root = os.path.abspath(os.path.join(os.path.dirname(str(File("SCsub").srcnode())), ".."))
source_root = os.path.join(project_root, "game")

env_spinning_cube.Append(CPPPATH=[
    os.path.join(source_root, "include"),
    os.path.join(source_root, "src"),
])
env_spinning_cube.Append(CPPDEFINES=["SPINNING_CUBE_MODULE"])

for cpp_file in sorted(os.listdir(os.path.join(source_root, "src"))):
    if cpp_file.endswith(".cpp"):
        env_spinning_cube.add_source_files(
            env.modules_sources,
            os.path.join(source_root, "src", cpp_file),
        )

env_spinning_cube.add_source_files(env.modules_sources, os.path.join(source_root, "register_types.cpp"))
env_spinning_cube.add_source_files(env.modules_sources, "register_types.cpp")
