"""Project initialization for gdcpps."""

from __future__ import annotations

import json
import re
from pathlib import Path


IDENTIFIER_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _load_versions(repo_root: Path) -> dict[str, object]:
    with (repo_root / "versions.json").open("r", encoding="utf-8") as handle:
        return json.load(handle)


def _validate_project_name(name: str) -> None:
    if not IDENTIFIER_RE.match(name):
        raise ValueError(
            "Project name must match ^[a-z][a-z0-9_]*$ so it can be reused as a module identifier."
        )


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def _manifest_text(project_name: str, godot_version: str) -> str:
    return f"""project:
  name: {project_name}
  module_name: {project_name}
  godot_version: {godot_version}

profiles:
  base: desktop-default
  web: web-small
  ios: mobile-default
  android: mobile-default

features:
  enable: []
  disable:
    - gdscript
    - advanced_gui

platforms:
  web:
    disable:
      - physics_2d
      - physics_3d
      - navigation_2d
      - navigation_3d
"""


def _root_readme_text(project_name: str) -> str:
    return f"""# {project_name}

Scaffolded by gdcpps.

This project is intended to use:

- GDExtension for debug iteration
- a custom Godot module build for release artifacts

Generated files are a starting point. Build orchestration will be provided by gdcpps tooling.
"""


def _project_godot_text(project_name: str, godot_version: str) -> str:
    return f"""; Engine configuration file.
; Generated by gdcpps.

[application]

config/name="{project_name}"
config/auto_accept_quit=true
run/main_scene="res://main.tscn"
config/features=PackedStringArray("{godot_version.rsplit('.', 1)[0]}")

[display]

window/size/viewport_width=1280
window/size/viewport_height=720

[rendering]

renderer/rendering_method="forward_plus"
"""


def _main_tscn_text(project_name: str, class_name: str) -> str:
    return f"""[gd_scene load_steps=2 format=3]

[sub_resource type="BoxMesh" id="BoxMesh_1"]

[node name="{project_name}" type="{class_name}"]

[node name="Cube" type="MeshInstance3D" parent="."]
mesh = SubResource("BoxMesh_1")

[node name="Camera3D" type="Camera3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1.25, 4)
current = true

[node name="DirectionalLight3D" type="DirectionalLight3D" parent="."]
transform = Transform3D(0.866025, -0.353553, 0.353553, 0, 0.707107, 0.707107, -0.5, -0.612372, 0.612372, 0, 2, 0)
"""


def _gdextension_text(module_name: str) -> str:
    return f"""[configuration]

entry_symbol = "{module_name}_library_init"
compatibility_minimum = "4.5"

[libraries]

windows.debug.x86_64 = "res://bin/lib{module_name}.windows.template_debug.x86_64.dll"
windows.release.x86_64 = "res://bin/lib{module_name}.windows.template_release.x86_64.dll"
linux.debug.x86_64 = "res://bin/lib{module_name}.linux.template_debug.x86_64.so"
linux.release.x86_64 = "res://bin/lib{module_name}.linux.template_release.x86_64.so"
macos.debug = "res://bin/lib{module_name}.macos.template_debug.framework"
macos.release = "res://bin/lib{module_name}.macos.template_release.framework"
web.debug.wasm32 = "res://bin/lib{module_name}.web.template_debug.wasm32.wasm"
web.release.wasm32 = "res://bin/lib{module_name}.web.template_release.wasm32.wasm"
"""


def _register_types_header_text(module_name: str) -> str:
    upper_name = module_name.upper()
    return f"""#pragma once

#ifdef {upper_name}_MODULE
#include "modules/register_module_types.h"
#elif defined({upper_name}_GDEXTENSION)
#include <godot_cpp/godot.hpp>
using namespace godot;
#endif

void initialize_{module_name}_module(ModuleInitializationLevel p_level);
void uninitialize_{module_name}_module(ModuleInitializationLevel p_level);
"""


def _register_types_source_text(module_name: str, class_name: str) -> str:
    upper_name = module_name.upper()
    return f"""#include "register_types.h"

#ifdef {upper_name}_GDEXTENSION
#include <gdextension_interface.h>
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/core/defs.hpp>
#include <godot_cpp/godot.hpp>
using namespace godot;
#elif defined({upper_name}_MODULE)
#include "core/object/class_db.h"
#endif

#include "src/{module_name}_main.h"

void initialize_{module_name}_module(ModuleInitializationLevel p_level) {{
\tif (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {{
\t\treturn;
\t}}
\tGDREGISTER_CLASS({class_name});
}}

void uninitialize_{module_name}_module(ModuleInitializationLevel p_level) {{
\tif (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {{
\t\treturn;
\t}}
}}

#ifdef {upper_name}_GDEXTENSION
extern "C" {{
GDExtensionBool GDE_EXPORT {module_name}_library_init(
\t\tGDExtensionInterfaceGetProcAddress p_get_proc_address,
\t\tGDExtensionClassLibraryPtr p_library,
\t\tGDExtensionInitialization *r_initialization) {{
\tGDExtensionBinding::InitObject init_obj(p_get_proc_address, p_library, r_initialization);
\tinit_obj.register_initializer(initialize_{module_name}_module);
\tinit_obj.register_terminator(uninitialize_{module_name}_module);
\tinit_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);
\treturn init_obj.init();
}}
}}
#endif
"""


def _gdcpp_header_text(module_name: str) -> str:
    upper_name = module_name.upper()
    return f"""#pragma once

#ifdef {upper_name}_GDEXTENSION

#include <godot_cpp/classes/node3d.hpp>
#include <godot_cpp/core/class_db.hpp>

using namespace godot;

#elif defined({upper_name}_MODULE)

#include "core/object/class_db.h"
#include "scene/3d/node_3d.h"

#else
#error "Define {upper_name}_GDEXTENSION or {upper_name}_MODULE before including gdcpp.h"
#endif
"""


def _game_header_text(module_name: str, class_name: str) -> str:
    _ = module_name
    return f"""#pragma once

#include "../include/gdcpp.h"

class {class_name} : public Node3D {{
\tGDCLASS({class_name}, Node3D)

protected:
\tstatic void _bind_methods();
\tvoid _notification(int p_what);

public:
\tvoid _ready();
\tvoid _process(double p_delta);
}};
"""


def _game_source_text(module_name: str, class_name: str) -> str:
    upper_name = module_name.upper()
    return f"""#include "{module_name}_main.h"

#ifdef {upper_name}_GDEXTENSION
#include <godot_cpp/classes/directional_light3d.hpp>
#include <godot_cpp/classes/environment.hpp>
#include <godot_cpp/classes/mesh_instance3d.hpp>
#include <godot_cpp/classes/plane_mesh.hpp>
#include <godot_cpp/classes/standard_material3d.hpp>
#include <godot_cpp/classes/world_environment.hpp>
#elif defined({upper_name}_MODULE)
#include "scene/3d/light_3d.h"
#include "scene/3d/mesh_instance_3d.h"
#include "scene/3d/world_environment.h"
#include "scene/resources/3d/primitive_meshes.h"
#include "scene/resources/environment.h"
#include "scene/resources/material.h"
#endif

void {class_name}::_bind_methods() {{
}}

void {class_name}::_notification(int p_what) {{
\tswitch (p_what) {{
\t\tcase NOTIFICATION_READY:
\t\t\t_ready();
\t\t\tbreak;
\t\tcase NOTIFICATION_PROCESS:
\t\t\t_process(get_process_delta_time());
\t\t\tbreak;
\t}}
}}

void {class_name}::_ready() {{
\tMeshInstance3D *cube = Object::cast_to<MeshInstance3D>(get_node_or_null(NodePath("Cube")));
\tif (cube) {{
\t\tRef<StandardMaterial3D> cube_material;
\t\tcube_material.instantiate();
\t\tcube_material->set_albedo(Color(0.18, 0.38, 0.92));
\t\tcube_material->set_metallic(0.18);
\t\tcube_material->set_roughness(0.14);
\t\tcube_material->set_emission(Color(0.20, 0.55, 1.0));
\t\tcube_material->set_emission_energy_multiplier(3.5);
\t\tcube->set_material_override(cube_material);
\t}}

\tif (!get_node_or_null(NodePath("Ground"))) {{
\t\tMeshInstance3D *ground = memnew(MeshInstance3D);
\t\tground->set_name("Ground");
\t\tRef<PlaneMesh> ground_mesh;
\t\tground_mesh.instantiate();
\t\tground_mesh->set_size(Vector2(12.0, 12.0));
\t\tground->set_mesh(ground_mesh);
\t\tground->set_position(Vector3(0.0, -0.5, 0.0));

\t\tRef<StandardMaterial3D> ground_material;
\t\tground_material.instantiate();
\t\tground_material->set_albedo(Color(0.07, 0.08, 0.10));
\t\tground_material->set_roughness(0.94);
\t\tground->set_material_override(ground_material);
\t\tadd_child(ground);
\t}}

\tDirectionalLight3D *light = Object::cast_to<DirectionalLight3D>(get_node_or_null(NodePath("DirectionalLight3D")));
\tif (light) {{
\t\tlight->set_shadow(true);
\t\tlight->set_shadow_mode(DirectionalLight3D::SHADOW_PARALLEL_4_SPLITS);
\t}}

\tWorldEnvironment *world_environment = Object::cast_to<WorldEnvironment>(get_node_or_null(NodePath("WorldEnvironment")));
\tif (!world_environment) {{
\t\tworld_environment = memnew(WorldEnvironment);
\t\tworld_environment->set_name("WorldEnvironment");
\t\tadd_child(world_environment);
\t}}

\tRef<Environment> environment;
\tenvironment.instantiate();
\tenvironment->set_background(Environment::BG_COLOR);
\tenvironment->set_bg_color(Color(0.03, 0.04, 0.06));
\tenvironment->set_ambient_source(Environment::AMBIENT_SOURCE_COLOR);
\tenvironment->set_ambient_light_color(Color(0.20, 0.22, 0.28));
\tenvironment->set_ambient_light_energy(1.0);
\tenvironment->set_glow_enabled(true);
\tenvironment->set_glow_level(0, 1.0);
\tenvironment->set_glow_level(1, 0.8);
\tenvironment->set_glow_normalized(true);
\tenvironment->set_glow_intensity(0.8);
\tenvironment->set_glow_strength(1.1);
\tenvironment->set_glow_mix(0.2);
\tenvironment->set_glow_bloom(0.15);
\tworld_environment->set_environment(environment);

\tset_process(true);
}}

void {class_name}::_process(double p_delta) {{
\tNode3D *cube = Object::cast_to<Node3D>(get_node_or_null(NodePath("Cube")));
\tif (cube) {{
\t\tcube->rotate_y(p_delta);
\t}}
}}
"""


def _module_config_text() -> str:
    return """def can_build(env, platform):
    return True


def configure(env):
    pass
"""


def _module_scsub_text(module_name: str) -> str:
    _ = module_name
    return """#!/usr/bin/env python

import importlib.util
import os
from glob import glob

Import("env")
Import("env_modules")

project_root = os.path.abspath(os.path.join(os.path.dirname(str(File("SCsub").srcnode())), ".."))
source_root = os.path.join(project_root, "game")
generated_helper = os.path.join(project_root, ".gdcpps", "generated", "module_build.py")

if os.path.exists(generated_helper):
    spec = importlib.util.spec_from_file_location("gdcpps_module_build", generated_helper)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load generated module helper: {generated_helper}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.configure_module(env, env_modules, project_root)
else:
    env_project = env_modules.Clone()
    env_project["redirect_build_objects"] = False
    env_project.Append(CPPPATH=[
        os.path.join(source_root, "include"),
        os.path.join(source_root, "src"),
    ])
    object_root = env.Dir("#bin/obj/external/gdcpps").abspath

    def object_target_for(source):
        source = os.path.abspath(source)
        try:
            relative_to_project = os.path.relpath(source, project_root)
            if not relative_to_project.startswith(".."):
                relative_object = os.path.splitext(relative_to_project)[0]
            else:
                raise ValueError
        except ValueError:
            drive, tail = os.path.splitdrive(source)
            relative_object = os.path.splitext(tail.lstrip("\\\\/"))[0]
            if drive:
                relative_object = os.path.join(drive.rstrip(":\\\\"), relative_object)
        return os.path.join(object_root, relative_object)

    for cpp_file in sorted(glob(os.path.join(source_root, "src", "*.cpp"))):
        built_objects = env_project.Object(target=object_target_for(cpp_file), source=cpp_file)
        env.modules_sources.extend(env_project.Flatten([built_objects]))

    for source in (
        os.path.join(source_root, "register_types.cpp"),
        os.path.join(project_root, "module", "register_types.cpp"),
    ):
        built_objects = env_project.Object(target=object_target_for(source), source=source)
        env.modules_sources.extend(env_project.Flatten([built_objects]))
"""


def _module_register_header_text(module_name: str) -> str:
    _ = module_name
    return """#pragma once

#include "modules/register_module_types.h"

void initialize_module_module(ModuleInitializationLevel p_level);
void uninitialize_module_module(ModuleInitializationLevel p_level);
"""


def _module_register_source_text(module_name: str, class_name: str) -> str:
    return f"""#include "register_types.h"
#include "core/object/class_db.h"

#include "{module_name}_main.h"

void initialize_module_module(ModuleInitializationLevel p_level) {{
\tif (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {{
\t\treturn;
\t}}
\tGDREGISTER_CLASS({class_name});
}}

void uninitialize_module_module(ModuleInitializationLevel p_level) {{
\tif (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {{
\t\treturn;
\t}}
}}
"""


def _dirs_file_text() -> str:
    return """# Generated directories
build/
deps/
artifacts/

# Compiler intermediates
*.o
*.obj
*.a
*.lib
*.exp
*.pdb
"""


def _bootstrap_note_text() -> str:
    return """This scaffold was generated by gdcpps.

Planned next steps:
- implement dependency sync
- generate debug build glue
- generate release build orchestration
"""


def _launcher_bat_text() -> str:
    return """@echo off
setlocal

if not defined GDCPPS_HOME (
    echo [gdcpps] error: GDCPPS_HOME environment variable is not set 1>&2
    echo [gdcpps] Please set GDCPPS_HOME to the path of your gdcpps installation 1>&2
    exit /b 1
)

set "LAUNCHER=%GDCPPS_HOME%\\gdcpps.bat"
if not exist "%LAUNCHER%" (
    echo [gdcpps] error: launcher not found at %LAUNCHER% 1>&2
    exit /b 1
)

:set_script_dir
set "PROJECT_DIR=%~dp0."

if "%~1"=="" (
    call "%LAUNCHER%" --help
    exit /b %ERRORLEVEL%
)

set "COMMAND=%~1"
if /I "%COMMAND%"=="deps" if /I "%~2"=="sync" goto deps_sync

shift
set "ARGS="
:collect_args
if "%~1"=="" goto dispatch
set ARGS=%ARGS% "%~1"
shift
goto collect_args

:deps_sync
shift
shift
set "ARGS="
:collect_deps_args
if "%~1"=="" goto dispatch_deps
set ARGS=%ARGS% "%~1"
shift
goto collect_deps_args

:dispatch_deps
call "%LAUNCHER%" deps sync "%PROJECT_DIR%" %ARGS%
exit /b %ERRORLEVEL%

:dispatch
if /I "%COMMAND%"=="build" (
    call "%LAUNCHER%" build --project "%PROJECT_DIR%" %ARGS%
    exit /b %ERRORLEVEL%
)
if /I "%COMMAND%"=="run" (
    call "%LAUNCHER%" run --project "%PROJECT_DIR%" %ARGS%
    exit /b %ERRORLEVEL%
)
if /I "%COMMAND%"=="upgrade" (
    call "%LAUNCHER%" upgrade --project "%PROJECT_DIR%" %ARGS%
    exit /b %ERRORLEVEL%
)
if /I "%COMMAND%"=="render-profile" (
    call "%LAUNCHER%" render-profile "%PROJECT_DIR%" %ARGS%
    exit /b %ERRORLEVEL%
)

call "%LAUNCHER%" %COMMAND% %ARGS%
exit /b %ERRORLEVEL%
"""


def _launcher_sh_text() -> str:
    return """#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

if [ -z "${GDCPPS_HOME:-}" ]; then
    echo "[gdcpps] error: GDCPPS_HOME environment variable is not set" >&2
    echo "[gdcpps] Please set GDCPPS_HOME to the path of your gdcpps installation" >&2
    exit 1
fi

LAUNCHER="$GDCPPS_HOME/gdcpps.sh"
if [ ! -f "$LAUNCHER" ]; then
    echo "[gdcpps] error: launcher not found at $LAUNCHER" >&2
    exit 1
fi

if [ "$#" -eq 0 ]; then
    exec "$LAUNCHER" --help
fi

COMMAND=$1
shift

case "$COMMAND" in
    build|run|upgrade)
        exec "$LAUNCHER" "$COMMAND" --project "$SCRIPT_DIR" "$@"
        ;;
    render-profile)
        exec "$LAUNCHER" "$COMMAND" "$SCRIPT_DIR" "$@"
        ;;
    deps)
        if [ "${1:-}" = "sync" ]; then
            shift
            exec "$LAUNCHER" deps sync "$SCRIPT_DIR" "$@"
        fi
        ;;
esac

exec "$LAUNCHER" "$COMMAND" "$@"
"""


def run(name: str, project_dir: str | None = None) -> int:
    repo_root = Path(__file__).resolve().parents[1]
    versions = _load_versions(repo_root)
    godot_version = str(versions["godot"]["version"])

    _validate_project_name(name)

    destination = Path(project_dir) if project_dir else Path.cwd() / name
    if destination.exists():
        raise FileExistsError(f"Destination already exists: {destination}")

    module_name = name
    class_name = "".join(part.capitalize() for part in module_name.split("_")) + "Main"

    _write_text(destination / "README.md", _root_readme_text(name))
    _write_text(destination / "gdcpps.yaml", _manifest_text(name, godot_version))
    _write_text(destination / ".gitignore", _dirs_file_text())
    _write_text(destination / ".gdcpps" / "README.txt", _bootstrap_note_text())
    _write_text(destination / "gdcpps.bat", _launcher_bat_text())
    _write_text(destination / "gdcpps.sh", _launcher_sh_text())

    _write_text(destination / "project" / "project.godot", _project_godot_text(name, godot_version))
    _write_text(destination / "project" / "main.tscn", _main_tscn_text(name, class_name))
    _write_text(destination / "project" / "bin" / f"{module_name}.gdextension", _gdextension_text(module_name))

    _write_text(destination / "game" / "include" / "gdcpp.h", _gdcpp_header_text(module_name))
    _write_text(destination / "game" / "register_types.h", _register_types_header_text(module_name))
    _write_text(destination / "game" / "register_types.cpp", _register_types_source_text(module_name, class_name))
    _write_text(destination / "game" / "src" / f"{module_name}_main.h", _game_header_text(module_name, class_name))
    _write_text(destination / "game" / "src" / f"{module_name}_main.cpp", _game_source_text(module_name, class_name))

    _write_text(destination / "module" / "config.py", _module_config_text())
    _write_text(destination / "module" / "SCsub", _module_scsub_text(module_name))
    _write_text(destination / "module" / "register_types.h", _module_register_header_text(module_name))
    _write_text(destination / "module" / "register_types.cpp", _module_register_source_text(module_name, class_name))

    for directory in ("build", "deps", "artifacts"):
        (destination / directory).mkdir(parents=True, exist_ok=True)

    print(f"Created gdcpps project at {destination}")
    return 0
