"""Manifest and profile resolution for gdcpps."""

from __future__ import annotations

from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover - exercised by CLI error handling
    raise RuntimeError("PyYAML is required to load gdcpps.yaml") from exc


PROFILE_DEFAULTS = {
    "desktop-default": {
        "target": "template_release",
        "optimize": "speed",
        "lto": "full",
    },
    "mobile-default": {
        "target": "template_release",
        "optimize": "size",
        "lto": "full",
    },
    "web-small": {
        "target": "template_release",
        "optimize": "size",
        "lto": "full",
        "threads": "no",
        "dlink_enabled": "no",
        "module_gdscript_enabled": "no",
        "disable_advanced_gui": "yes",
    },
}


FEATURE_FLAG_MAP = {
    "gdscript": {
        "enable": {"module_gdscript_enabled": "yes"},
        "disable": {"module_gdscript_enabled": "no"},
    },
    "advanced_gui": {
        "enable": {"disable_advanced_gui": "no"},
        "disable": {"disable_advanced_gui": "yes"},
    },
    "physics_2d": {
        "enable": {
            "disable_physics_2d": "no",
            "module_godot_physics_2d_enabled": "yes",
        },
        "disable": {
            "disable_physics_2d": "yes",
            "module_godot_physics_2d_enabled": "no",
        },
    },
    "physics_3d": {
        "enable": {
            "disable_physics_3d": "no",
            "module_godot_physics_3d_enabled": "yes",
        },
        "disable": {
            "disable_physics_3d": "yes",
            "module_godot_physics_3d_enabled": "no",
        },
    },
    "navigation_2d": {
        "enable": {"module_navigation_2d_enabled": "yes"},
        "disable": {"module_navigation_2d_enabled": "no"},
    },
    "navigation_3d": {
        "enable": {
            "disable_navigation_3d": "no",
            "module_navigation_3d_enabled": "yes",
        },
        "disable": {
            "disable_navigation_3d": "yes",
            "module_navigation_3d_enabled": "no",
        },
    },
    "threads": {
        "enable": {"threads": "yes"},
        "disable": {"threads": "no"},
    },
}


def load_manifest(project_root: Path) -> dict:
    manifest_path = project_root / "gdcpps.yaml"
    with manifest_path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}

    if not isinstance(data, dict):
        raise ValueError(f"Manifest must be a mapping: {manifest_path}")

    return data


def _get_profile_name(manifest: dict, platform: str) -> str:
    profiles = manifest.get("profiles", {})
    if not isinstance(profiles, dict):
        raise ValueError("profiles must be a mapping")

    profile_name = profiles.get(platform, profiles.get("base", "desktop-default"))
    if profile_name not in PROFILE_DEFAULTS:
        raise ValueError(f"Unknown profile '{profile_name}' for platform '{platform}'")
    return profile_name


def _collect_feature_lists(manifest: dict, platform: str) -> tuple[list[str], list[str]]:
    features = manifest.get("features", {})
    platforms = manifest.get("platforms", {})
    platform_cfg = platforms.get(platform, {}) if isinstance(platforms, dict) else {}

    enabled = list(features.get("enable", []))
    disabled = list(features.get("disable", []))

    enabled.extend(platform_cfg.get("enable", []))
    disabled.extend(platform_cfg.get("disable", []))
    return enabled, disabled


def resolve_flags(manifest: dict, platform: str) -> dict[str, str]:
    profile_name = _get_profile_name(manifest, platform)
    flags = dict(PROFILE_DEFAULTS[profile_name])

    enabled, disabled = _collect_feature_lists(manifest, platform)

    for feature_name in disabled:
        feature = FEATURE_FLAG_MAP.get(feature_name)
        if feature is None:
            raise ValueError(f"Unknown disabled feature '{feature_name}'")
        flags.update(feature["disable"])

    for feature_name in enabled:
        feature = FEATURE_FLAG_MAP.get(feature_name)
        if feature is None:
            raise ValueError(f"Unknown enabled feature '{feature_name}'")
        flags.update(feature["enable"])

    return flags


def render_profile(flags: dict[str, str]) -> str:
    lines = [
        "# Generated by gdcpps.",
        "# Do not edit by hand; regenerate from gdcpps.yaml.",
        "",
    ]
    for key in sorted(flags):
        lines.append(f'{key} = "{flags[key]}"')
    lines.append("")
    return "\n".join(lines)
